### PR TITLE
added sorting of mz values

### PR DESCRIPTION
**Pull request by michaelwitting**
Added sorting of m/z values. In rare cases I observed that m/z values in mgf files are not sorted, which leads to an error. This fixes the import of such files.

### CODE REVIEW

**Review by jorainer — CHANGES_REQUESTED** [review]
Thanks for the fix. it might however be more efficient to only order the matrix if it is in facto unsorted:

```r
if (is.unsorted(ms[, 1L]))
    ms <- ms[order(mz[, 1L]), , drop = FALSE]
```

`is.unsorted` is faster than actually sorting the `matrix`, thus, we are only sorting it if it is necessary (and `is.unsorted` will break as soon as it finds one element that is not `>=` the previous).

**Comment by lgatto** [comment]
We had that same discussion for another back-end - did we do this silently or did we output a message? 

@michaelwitting - once you have updated the PR with @jorainer' comment, could you also add yourself as a contributor in the DESCRIPTION file.

**Comment by michaelwitting** [comment]
I'm not aware of any public message. Changes are coming.

**Comment by jorainer** [comment]
@lgatto in this particular case I would silently order the m/z value. The other discussion was in `MsCoreUtils` and related to a function there. For that we decided to throw an error if values were not sorted. Here, I think silently ordering is OK.

**Review by jorainer — APPROVED** [review]
All good from my side. Will merge and push to BioC.

**Pull request merged**
