### PR TITLE
Speedup `readMgf`

### PR DESCRIPTION
**Pull request by Adafede**
Dear r4MS team, happy new year!

I recently had to read some large MGF files and found the reader could be faster.
This is my attempt to make things approx 2 times faster, I believe things could still be optimized a lot but 50% cut is already good enough to justify a PR (I guess).

- It adds an additional dependency, `stringi`, which is faster than base operations.
- It uses `mapply` instead of the previous `for`loop.
- Some additional linting of brackets, etc.

### CODE REVIEW

**Comment by lgatto** [comment]
A few quick comments:
- Could you provide your profiling and benchmarking results as part of the PR? It would be useful for the review. 
- We aren't keen on adding additional dependencies, hence the importance of profiling, to assess how much is gained by `stringi`.
-  Finally, there are other _extra_ modifications in the code, such as adding `package::` or trivial styling, that shouldn't be part of the speed-up PR.

**Comment by Adafede** [comment]
@lgatto thank you for your quick feedback!
I'll provide the profiling w/o stringi, probably next week.
Regarding the "extras", shall I completely remove them?
The additional brackets make the code more readable to me and I could not see any hurt, would you like them in another PR or not at all?

**Comment by lgatto** [comment]
I don't remember of we specifically mention the brackets in our [coding style](https://rformassspectrometry.github.io/RforMassSpectrometry/articles/RforMassSpectrometry.html#coding-style), and I don't think it is an issue per se. I think the PR is easier to handle if it ignore the code styling altogether.

**Comment by sgibb** [comment]
Dear Adriano,

thanks for your PR and for reminding me about the `fixed = TRUE` argument in `grep` (I open another PR that introduces only `fixed` and `perl` arguments to `grep` and `strsplit`: #27)

At least for me your implementation isn't working for any of the 4 `MsBackendMgf` example files (throws different errors for 1, 2, and 4 and returns wrong results for 3; hopefully I didn't have a copy&paste error):

```r
readMgf.adafede <- function(f, msLevel = 2L,
                    mapping = Spectra::spectraVariableMapping(MsBackendMgf::MsBackendMgf()), ...) {
    requireNamespace("MsBackendMgf", quietly = TRUE)
    if (length(f) != 1L) {
      stop("Please provide a single mgf file.")
    }
    mgf <- scan(
      file = f,
      what = "",
      sep = "\n",
      quote = "",
      allowEscapes = FALSE,
      quiet = TRUE
    )
    ## From http://www.matrixscience.com/help/data_file_help.html#GEN
    ## Comment lines beginning with one of the symbols #;!/ can be
    ## included, but only outside of the BEGIN IONS and END IONS
    ## statements that delimit an MS/MS dataset.
    cmts <-
      which(stringi::stri_detect_regex(str = mgf,
                                       pattern = "^[#;!/]") == TRUE)

    if (length(cmts)) {
      mgf <- mgf[-cmts]
    }

    begin <- grep(pattern = "BEGIN IONS",
                  x = mgf,
                  fixed = TRUE) + 1L

    end <- grep(pattern = "END IONS",
                x = mgf,
                fixed = TRUE) - 1L

    sp <- mapply(function(b, e) {
      .extract_mgf_spectrum.adafede(mgf = mgf[b:e], mapping = mapping)
    },
    begin,
    end)

    res <- S4Vectors::DataFrame(MsCoreUtils::rbindFill(sp))

    spv <- Spectra::coreSpectraVariables()
    spv <- spv[!names(spv) %in% c("mz", "intensity")]
    for (i in seq_along(res)) {
        if (all(lengths(res[[i]]) == 1))
            res[[i]] <- unlist(res[[i]])
        if (any(col <- names(spv) == colnames(res)[i]))
            res[[i]] <- as(res[[i]], spv[col][1])
    }

    res$mz <- IRanges::NumericList(res$mz, compress = FALSE)
    res$intensity <- IRanges::NumericList(res$intensity, compress = FALSE)
    res$dataOrigin <- f
    if(!"msLevel" %in% colnames(res)) {
      res$msLevel <- as.integer(msLevel)
    }

    res
}

.extract_mgf_spectrum.adafede <- function(mgf, mapping) {
  desc.idx <-
    which(stringi::stri_detect_regex(str = mgf, pattern = "=") == TRUE)
    desc <- mgf[desc.idx]
    spec <- mgf[-desc.idx]

    ms <- stringi::stri_split_fixed(str = spec,
                                    pattern = " ",
                                    simplify = TRUE)
    mode(ms) <- "double"

    if (!length(ms) || length(ms) == 1L) {
      ms <- matrix(numeric(), ncol = 2L)
    }

    if(nrow(ms) > 1) {
      if (is.unsorted(ms[, 1L])) {
        ms <- ms[order(ms[, 1L]), , drop = FALSE]
      }
    }

    r <- regexpr("=", desc, fixed = TRUE)
    desc <- setNames(substring(desc, r + 1L, nchar(desc)),
                     substring(desc, 1L, r - 1L))
    title <- unname(desc["TITLE"])

    desc[c("PEPMASS", "PEPMASSINT")] <-
      stringi::stri_split_fixed(str = desc["PEPMASS"],
                                pattern = " ")[[1L]][seq_len(2)]

    ## Use all fields in the MGF renaming the ones specified by mapping.
    if ("CHARGE" %in% names(desc)) {
      desc["CHARGE"] <- .format_charge.adafede(desc["CHARGE"])
    }
    idx <- match(names(desc), mapping)
    not_na <- !is.na(idx)
    if (any(not_na)) {
      names(desc)[not_na] <- names(mapping)[idx][not_na]
    }
    res <- data.frame(matrix(desc, nrow = 1,
                             dimnames = list(NULL, names(desc))))
    res$mz = list(ms[, 1L])
    res$intensity = list(ms[, 2L])
    res
}

.format_charge.adafede <- function(x) {
    res <- sub(pattern = "[+-]",
               replacement = "",
               x = x)
    negs <- grep(pattern = "-$", x = x)
    if (length(negs)) {
      res[negs] <- paste0("-", res[negs])
    }
    res
}

library("Spectra")
library("microbenchmark")

fls <- dir(system.file("extdata", package = "MsBackendMgf"),
            full.names = TRUE, pattern = "mgf$")

all.equal(MsBackendMgf:::readMgf(fls[3L]), readMgf.adafede(fls[3L]))
#>  [1] "Lengths: 13, 5"                                                                                      
#>  [2] "Names: Lengths (13, 5) differ (string compare on first 5)"                                           
#>  [3] "Names: 5 string mismatches"                                                                          
#>  [4] "Attributes: < Component \"listData\": Names: 5 string mismatches >"                                  
#>  [5] "Attributes: < Component \"listData\": Length mismatch: comparison on first 5 components >"           
#>  [6] "Attributes: < Component \"listData\": Component 1: Modes: numeric, character >"                      
#>  [7] "Attributes: < Component \"listData\": Component 1: Lengths: 1, 12 >"                                 
#>  [8] "Attributes: < Component \"listData\": Component 1: names for current but not for target >"           
#>  [9] "Attributes: < Component \"listData\": Component 1: target is numeric, current is character >"        
#> [10] "Attributes: < Component \"listData\": Component 2: Modes: numeric, S4 >"                             
#> [11] "Attributes: < Component \"listData\": Component 2: Lengths: 1, 12 >"                                 
#> [12] "Attributes: < Component \"listData\": Component 2: Attributes: < target is NULL, current is list > >"
#> [13] "Attributes: < Component \"listData\": Component 2: target is numeric, current is SimpleNumericList >"
#> [14] "Attributes: < Component \"listData\": Component 3: Modes: numeric, S4 >"                             
#> [15] "Attributes: < Component \"listData\": Component 3: Lengths: 1, 12 >"                                 
#> [16] "Attributes: < Component \"listData\": Component 3: Attributes: < target is NULL, current is list > >"
#> [17] "Attributes: < Component \"listData\": Component 3: target is numeric, current is SimpleNumericList >"
#> [18] "Attributes: < Component \"listData\": Component 4: Modes: logical, character >"                      
#> [19] "Attributes: < Component \"listData\": Component 4: Lengths: 1, 12 >"                                 
#> [20] "Attributes: < Component \"listData\": Component 4: target is logical, current is character >"        
#> [21] "Attributes: < Component \"listData\": Component 5: Numeric: lengths (1, 12) differ >"                
#> [22] "Attributes: < Component \"nrows\": Mean relative difference: 11 >"                                   
#> [23] "Attributes: < Component \"rownames\": Modes of target, current: name, character >"                   
#> [24] "Attributes: < Component \"rownames\": target, current do not match when deparsed >"

readMgf.adafede(fls[1L])
#> Error in `[[<-`(`*tmp*`, i, value = c(TITLE = "File193 Spectrum1719 scans: 2162", : 34 elements in value to replace 8 elements
readMgf.adafede(fls[2L])
#> Warning in mde(x): NAs introduced by coercion
#> Error in if (is.unsorted(ms[, 1L])) {: missing value where TRUE/FALSE needed
readMgf.adafede(fls[4L])
#> Error in `[[<-`(`*tmp*`, i, value = c(TITLE = "File193 Spectrum1719 scans: 2162", : 35 elements in value to replace 9 elements
```

> * It adds an additional dependency, `stringi`, which is faster than base operations.

While you are right, that `stringi` may be faster in general than base regexp functions that seems not to be true for the perl engine (this may be different on larger files/more matching):

``` r
fls <- dir(
    system.file("extdata", package = "MsBackendMgf"),
    full.names = TRUE,
    pattern = "mgf$"
)[2L]

mgf <- scan(
    file = fls,
    what = "",
    sep = "\n",
    quote = "",
    allowEscapes = FALSE,
    quiet = TRUE
)

library("stringi")
library("microbenchmark")

.stri1 <- function(f)which(stringi::stri_detect_regex(str = mgf, pattern = "^[#;!/]") == TRUE)
.stri2 <- function(f)which(stri_detect_regex(str = mgf, pattern = "^[#;!/]"))
.grep <- function(f)grep("^[#;!/]", mgf)
.grepp <- function(f)grep("^[#;!/]", mgf, perl = TRUE)


microbenchmark(.stri1(mgf), .stri2(mgf), .grep(mgf), .grepp(mgf), check = "identical")
#> Unit: microseconds
#>         expr     min       lq     mean   median       uq       max neval
#>  .stri1(mgf) 407.807 440.7860 543.3602 477.8125 532.6115  4301.703   100
#>  .stri2(mgf) 417.693 445.5455 513.8350 474.5415 521.8955  2872.616   100
#>   .grep(mgf) 841.581 901.7430 980.1349 925.2210 990.1190  3045.771   100
#>  .grepp(mgf)  90.849 100.1890 407.1757 107.7465 119.7885 29171.258   100
```

`fixed = TRUE` is even faster:

```r
microbenchmark(
    default = grep("BEGIN IONS", mgf),
    fixed = grep("BEGIN IONS", mgf, fixed = TRUE),
    perl = grep("BEGIN IONS", mgf, perl = TRUE)
)
#> Unit: microseconds
#>     expr     min      lq      mean   median       uq      max neval
#>  default 609.953 661.870 732.36540 711.6275 792.5695 1158.951   100
#>    fixed  44.987  47.818  55.17656  53.2375  59.3190   95.152   100
#>     perl  97.155 103.036 120.17031 113.1000 122.9030  303.822   100
```

> * It uses `mapply` instead of the previous `for`loop.

I doubt that `mapply` is any faster than a `for` loop. You may prefer it for readability.

As @lgatto already mentioned, we are very cautious when it comes to new dependencies. But feel free to fix this PR and provide a working example with a benchmark. If the runtime decrease by ~ 50% it is worth to consider a new dependency.

BTW: please don't use `::` if not really necessary (same function from two different imported packages) - use `import`/`NAMESPACE` instead. `::` is a function that does a lot of dispatching that needs time.

**Comment by Adafede** [comment]
Closing in favor of #27

**Pull request closed without merging**
