### PR TITLE
readMgf: use fixed/perl for regexp

### PR DESCRIPTION
**Pull request by sgibb**
This PR is a follow-up PR to #26 .
Thanks to @Adafede to start this refactoring and to remind me about `grep(..., fixed = TRUE)`.

On the example file there is no improvement in runtime. I guess it depends on the number of spectra in the mgf file
(mean is worse than the older implementation, median better for our small example files; on a 4 Mb example file the fixed/perl implementation offers small improvments).

It would be great if someone could test this with a real world example.

```r

readMgf.old <- function(f, msLevel = 2L,
                    mapping = spectraVariableMapping(MsBackendMgf()), ...) {
    requireNamespace("MsBackendMgf", quietly = TRUE)
    if (length(f) != 1L)
        stop("Please provide a single mgf file.")
    mgf <- scan(file = f, what = "",
                sep = "\n", quote = "",
                allowEscapes = FALSE,
                quiet = TRUE)
    ## From http://www.matrixscience.com/help/data_file_help.html#GEN
    ## Comment lines beginning with one of the symbols #;!/ can be
    ## included, but only outside of the BEGIN IONS and END IONS
    ## statements that delimit an MS/MS dataset.
    cmts <- grep("^[#;!/]", mgf)
    if (length(cmts))
        mgf <- mgf[-cmts]

    begin <- grep("BEGIN IONS", mgf) + 1L
    end <- grep("END IONS", mgf) - 1L
    n <- length(begin)
    sp <- vector("list", length = n)

    for (i in seq(along = sp))
        sp[[i]] <- .extract_mgf_spectrum.old(mgf[begin[i]:end[i]],
                                         mapping = mapping)

    res <- DataFrame(rbindFill(sp))

    spv <- coreSpectraVariables()
    spv <- spv[!names(spv) %in% c("mz", "intensity")]
    for (i in seq_along(res)) {
        if (all(lengths(res[[i]]) == 1))
            res[[i]] <- unlist(res[[i]])
        if (any(col <- names(spv) == colnames(res)[i]))
            res[[i]] <- as(res[[i]], spv[col][1])
    }

    res$mz <- IRanges::NumericList(res$mz, compress = FALSE)
    res$intensity <- IRanges::NumericList(res$intensity, compress = FALSE)
    res$dataOrigin <- f
    if(!"msLevel" %in% colnames(res)) {
      res$msLevel <- as.integer(msLevel)
    }

    res
}

.extract_mgf_spectrum.old <- function(mgf, mapping) {
    ## grep description
    desc.idx <- grep("=", mgf)
    desc <- mgf[desc.idx]
    spec <- mgf[-desc.idx]

    ms <- do.call(rbind, strsplit(spec, "[[:space:]]+"))
    mode(ms) <- "double"

    if (!length(ms) || length(ms) == 1L)
        ms <- matrix(numeric(), ncol = 2L)

    if(nrow(ms) > 1) {
      if (is.unsorted(ms[, 1L])) {
        ms <- ms[order(ms[, 1L]), , drop = FALSE]
      }
    }

    r <- regexpr("=", desc, fixed = TRUE)
    desc <- setNames(substring(desc, r + 1L, nchar(desc)),
                     substring(desc, 1L, r - 1L))
    title <- unname(desc["TITLE"])

    desc[c("PEPMASS", "PEPMASSINT")] <-
        strsplit(desc["PEPMASS"], "[[:space:]]+")[[1L]][seq_len(2)]

    ## Use all fields in the MGF renaming the ones specified by mapping.
    if ("CHARGE" %in% names(desc))
        desc["CHARGE"] <- .format_charge.old(desc["CHARGE"])
    idx <- match(names(desc), mapping)
    not_na <- !is.na(idx)
    if (any(not_na))
        names(desc)[not_na] <- names(mapping)[idx][not_na]
    res <- data.frame(matrix(desc, nrow = 1,
                             dimnames = list(NULL, names(desc))))
    res$mz = list(ms[, 1L])
    res$intensity = list(ms[, 2L])
    res
}

.format_charge.old <- function(x) {
    res <- sub("[+-]", "", x)
    negs <- grep("-$", x)
    if (length(negs))
        res[negs] <- paste0("-", res[negs])
    res
}

readMgf <- function(f, msLevel = 2L,
                    mapping = spectraVariableMapping(MsBackendMgf()), ...) {
    requireNamespace("MsBackendMgf", quietly = TRUE)
    if (length(f) != 1L)
        stop("Please provide a single mgf file.")
    mgf <- scan(file = f, what = "",
                sep = "\n", quote = "",
                allowEscapes = FALSE,
                quiet = TRUE)
    ## From http://www.matrixscience.com/help/data_file_help.html#GEN
    ## Comment lines beginning with one of the symbols #;!/ can be
    ## included, but only outside of the BEGIN IONS and END IONS
    ## statements that delimit an MS/MS dataset.
    cmts <- grep("^[#;!/]", mgf, perl = TRUE)
    if (length(cmts))
        mgf <- mgf[-cmts]

    begin <- grep("BEGIN IONS", mgf, fixed = TRUE) + 1L
    end <- grep("END IONS", mgf, fixed = TRUE) - 1L
    n <- length(begin)
    sp <- vector("list", length = n)

    for (i in seq(along = sp))
        sp[[i]] <- .extract_mgf_spectrum(mgf[begin[i]:end[i]],
                                         mapping = mapping)

    res <- DataFrame(rbindFill(sp))

    spv <- coreSpectraVariables()
    spv <- spv[!names(spv) %in% c("mz", "intensity")]
    for (i in seq_along(res)) {
        if (all(lengths(res[[i]]) == 1))
            res[[i]] <- unlist(res[[i]])
        if (any(col <- names(spv) == colnames(res)[i]))
            res[[i]] <- as(res[[i]], spv[col][1])
    }

    res$mz <- IRanges::NumericList(res$mz, compress = FALSE)
    res$intensity <- IRanges::NumericList(res$intensity, compress = FALSE)
    res$dataOrigin <- f
    if(!"msLevel" %in% colnames(res)) {
      res$msLevel <- as.integer(msLevel)
    }

    res
}

.extract_mgf_spectrum <- function(mgf, mapping) {
    ## grep description
    desc.idx <- grep("=", mgf, fixed = TRUE)
    desc <- mgf[desc.idx]
    spec <- mgf[-desc.idx]

    ms <- do.call(rbind, strsplit(spec, "[[:space:]]+", perl = TRUE))
    mode(ms) <- "double"

    if (!length(ms) || length(ms) == 1L)
        ms <- matrix(numeric(), ncol = 2L)

    if(nrow(ms) > 1) {
      if (is.unsorted(ms[, 1L])) {
        ms <- ms[order(ms[, 1L]), , drop = FALSE]
      }
    }

    r <- regexpr("=", desc, fixed = TRUE)
    desc <- setNames(substring(desc, r + 1L, nchar(desc)),
                     substring(desc, 1L, r - 1L))
    title <- unname(desc["TITLE"])

    desc[c("PEPMASS", "PEPMASSINT")] <-
        strsplit(desc["PEPMASS"], "[[:space:]]+", perl = TRUE)[[1L]][c(1L, 2L)]

    ## Use all fields in the MGF renaming the ones specified by mapping.
    if ("CHARGE" %in% names(desc))
        desc["CHARGE"] <- .format_charge(desc["CHARGE"])
    idx <- match(names(desc), mapping)
    not_na <- !is.na(idx)
    if (any(not_na))
        names(desc)[not_na] <- names(mapping)[idx][not_na]
    res <- data.frame(matrix(desc, nrow = 1,
                             dimnames = list(NULL, names(desc))))
    res$mz = list(ms[, 1L])
    res$intensity = list(ms[, 2L])
    res
}

.format_charge <- function(x) {
    res <- sub("[+-]", "", x, perl = TRUE)
    negs <- which(endsWith(x, "-"))
    if (length(negs))
        res[negs] <- paste0("-", res[negs])
    res
}

library("Spectra")
library("microbenchmark")

fls <- dir(system.file("extdata", package = "MsBackendMgf"),
            full.names = TRUE, pattern = "mgf$")

microbenchmark(
    readMgf.old(fls[2L]),
    readMgf(fls[2L]),
    times = 10
)
#> Unit: milliseconds
#>                  expr      min       lq     mean   median       uq      max
#>  readMgf.old(fls[2L]) 123.5384 127.4963 160.3947 132.5820 157.9930 375.3517
#>      readMgf(fls[2L]) 123.4549 125.9856 162.1121 130.5777 143.3893 431.5881
#>  neval
#>     10
#>     10

## a 4 Mb example file
download.file(
    "http://mendel.bii.a-star.edu.sg/mass-spectrometry/MSCleaner-2.0/examples/bsa_run1_merge.mgf",
    "bsa.mgf"
)

microbenchmark(
    readMgf.old("bsa.mgf"),
    readMgf("bsa.mgf"),
    times = 3
)
#> Unit: seconds
#>                    expr      min       lq     mean  median       uq      max
#>  readMgf.old("bsa.mgf") 4.877549 5.172305 5.365902 5.46706 5.610078 5.753097
#>      readMgf("bsa.mgf") 3.905841 4.519971 4.926819 5.13410 5.437308 5.740517
#>  neval
#>      3
#>      3
```

### CODE REVIEW

**Comment by Adafede** [comment]
Thank you for doing it properly and without the additional extras/dpendencies @sgibb!

My version worked faster on my use-case, but not other MGFs I tested afterward, after your remark.
I can confirm it works at the same speed on "normal/small" real world example MGFs:
- https://raw.githubusercontent.com/taxonomicallyinformedannotation/tima-example-files/main/example_spectra.mgf

But when it comes to larger ones (100MB), there is a small gain.
- https://www.swisstransfer.com/d/149e462a-0482-43d5-9323-849aa71068af (valid 30 days)

```
> microbenchmark::microbenchmark(
+   MsBackendMgf::readMgf(f = file_2),
+   readMgf(f = file_2),
+   times = 5
+ )
Unit: seconds
                              expr      min       lq     mean   median       uq      max neval cld
 MsBackendMgf::readMgf(f = file_2) 24.11220 24.15295 25.41189 25.06259 26.18652 27.54518     5  a 
               readMgf(f = file_2) 21.61442 21.92481 22.63885 22.04373 23.34028 24.27101     5   b
```

It was more pronounced before, but I totally recognize the use case might not justify an additional dependency.

**Comment by sgibb** [comment]
Thanks for testing. I didn't do any profiling but I guess we spend more time in creating the objects than parsing the file.

06.01.2024 07:45:11 Adriano Rutz ***@***.***>:

**Comment by jorainer** [comment]
Thanks @Adafede and @sgibb ! I will run some more tests also on larger Mgf files (e.g. on those from GNPS).

**Comment by Adafede** [comment]
@jorainer If there is anything I can do to help reading files like https://zenodo.org/records/10160791 faster, very happy to! (the file I sent above are the first 10,000 spectra of it)

**Comment by jorainer** [comment]
I'm OK with this PR, but added some more changes to this (PR #28 ) - I will compare performance of the additional changes with the ones here in #28.

**Comment by lgatto** [comment]
Fine by me. Thank you @Adafede - could you add yourself as a contributor in the DESCRIPTION file.

**Comment by Adafede** [comment]
@lgatto My contribution was more of a trial and then @sgibb and @jorainer took over... 
And it looks like this PR already was superseeded by #28 in the meantime, don't know how you will handle the merges! 😅

**Comment by jorainer** [comment]
@Adafede , I agree with Laurent that your contribution was valuable. I'll add you as contributor (using your ORCID and work email)

**Comment by jorainer** [comment]
This PR contains now @sgibb 's improvement and some refactoring I did on top of it. In the end, performance was improved (slightly).

**Comment by jorainer** [comment]
Also pushed to BioC

**Pull request merged**
